version: "3.8"
services:

  postgres_db:
    image:  postgres:latest
    restart: unless-stopped #  always restarts a container, except when the container is stopped (manually or otherwise).
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - pgres-db:/var/lib/postgresql/data


volumes:
  pgres-db:


conn=psycopg2.connect(
  database="airflow",
  user="airflow",
  host="postgres_db",
  password="airflow"
)

conn=psycopg2.connect(
  database="airflow",
  user="airflow",
  host="localhost",
  password="airflow"
)